# Generated by Django 3.2.4 on 2021-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
